///////////////////////////////////////////////////////////////////////////
//
//  Autogenerated by bindgen.py
//
///////////////////////////////////////////////////////////////////////////


#pragma once
#ifndef RHI_PLATFORM_H_
#define RHI_PLATFORM_H_


#ifdef RHI_GLFW
#include <GLFW/glfw3.h>
#include <GLFW/glfw3native.h>
#endif // RHI_GLFW

#ifdef RHI_SDL
#include <SDL.h>
#endif // RHI_SDL


#if defined(__cplusplus)
extern "C" {
#endif

#if !defined(RHI_SKIP_DECLARATIONS)


#ifdef RHI_GLFW
RHI_API void RHI_setWindowHandleGLFW(const GLFWwindow * window, RHI_WindowHandle windowHandle);
#endif // RHI_GLFW

#ifdef RHI_SDL
RHI_API void RHI_setWindowHandleSDL(const SDL_Window * window, RHI_WindowHandle windowHandle);
#endif // RHI_SDL


#endif // !defined(RHI_SKIP_DECLARATIONS)

#if defined(__cplusplus)
} // extern "C"
#endif

#endif // RHI_PLATFORM_H_

