///////////////////////////////////////////////////////////////////////////
//
//  Autogenerated by bindgen.py
//
///////////////////////////////////////////////////////////////////////////


#pragma once
#ifndef RHI_RESOURCELOADER_ENUMS_H_
#define RHI_RESOURCELOADER_ENUMS_H_

typedef enum RHI_TextureContainerType
{
    RHI_TEXTURE_CONTAINER_DEFAULT = 0,
    RHI_TEXTURE_CONTAINER_DDS,
    RHI_TEXTURE_CONTAINER_KTX,
    RHI_TEXTURE_CONTAINER_GNF,
    RHI_TEXTURE_CONTAINER_BASIS,
    RHI_TEXTURE_CONTAINER_SVT
} RHI_TextureContainerType;

typedef enum RHI_GeometryLoadFlags
{
    RHI_GEOMETRY_LOAD_FLAG_SHADOWED = 0x1,
    RHI_GEOMETRY_LOAD_FLAG_STRUCTURED_BUFFERS = 0x2
} RHI_GeometryLoadFlags;

typedef enum RHI_ShaderStageLoadFlags
{
    RHI_SHADER_STAGE_LOAD_FLAG_NONE = 0x0,
    RHI_SHADER_STAGE_LOAD_FLAG_ENABLE_PS_PRIMITIVEID = 0x1
} RHI_ShaderStageLoadFlags;



#endif // RHI_RESOURCELOADER_ENUMS_H_

