///////////////////////////////////////////////////////////////////////////
//
//  Autogenerated by bindgen.py
//
///////////////////////////////////////////////////////////////////////////


#pragma once
#ifndef RHI_SHADERREFLECTION_H_
#define RHI_SHADERREFLECTION_H_


#include "export.h"
#include "shaderreflection_enums.h"
#include "shaderreflection_structs.h"


#if defined(__cplusplus)
extern "C" {
#endif


#if !defined(RHI_SKIP_DECLARATIONS)

RHI_API void RHI_destroyShaderReflection(RHI_ShaderReflection * pReflection);
RHI_API void RHI_createPipelineReflection(RHI_ShaderReflection * pReflection, uint32_t stageCount, RHI_PipelineReflection * pOutReflection);
RHI_API void RHI_destroyPipelineReflection(RHI_PipelineReflection * pReflection);


#endif // !defined(RHI_SKIP_DECLARATIONS)

#if defined(__cplusplus)
} // extern "C"
#endif

#endif // RHI_SHADERREFLECTION_H_

