///////////////////////////////////////////////////////////////////////////
//
//  Autogenerated by bindgen.py
//
///////////////////////////////////////////////////////////////////////////


#pragma once
#ifndef RHI_SHADERREFLECTION_ENUMS_H_
#define RHI_SHADERREFLECTION_ENUMS_H_

typedef enum RHI_TextureDimension
{
    RHI_TEXTURE_DIM_1D,
    RHI_TEXTURE_DIM_2D,
    RHI_TEXTURE_DIM_2DMS,
    RHI_TEXTURE_DIM_3D,
    RHI_TEXTURE_DIM_CUBE,
    RHI_TEXTURE_DIM_1D_ARRAY,
    RHI_TEXTURE_DIM_2D_ARRAY,
    RHI_TEXTURE_DIM_2DMS_ARRAY,
    RHI_TEXTURE_DIM_CUBE_ARRAY,
    RHI_TEXTURE_DIM_COUNT,
    RHI_TEXTURE_DIM_UNDEFINED
} RHI_TextureDimension;



#endif // RHI_SHADERREFLECTION_ENUMS_H_

